---
- hosts: azure
  become: true

  vars:
    docker_linux_ubuntu: https://download.docker.com/linux/ubuntu

  vars_files:
    - vault.yml

  handlers:
    - name: update_apt_cache
      apt: 
        update_cache: true

    - name: show_output
      debug:
        var: output

    - name: restart_nginx
      community.docker.docker_compose_v2:
        project_src: "{{ docker_env.PROJECT_SRC }}"
        services:
          - nginx
        state: restarted
      register: output
      notify: show_output

  pre_tasks:
    - name: Create project root directory
      file:
        path: "{{ docker_env.PROJECT_SRC }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Install required packages
      apt:
        name: ca-certificates
        state: present

    - name: Add GPG key
      apt_key:
        url: "{{ docker_linux_ubuntu }}/gpg"
        state: present

    - name: Add Docker repository to APT sources
      apt_repository:
        repo: "deb {{ docker_linux_ubuntu }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Copy Docker compose file
      copy:
        src: ./docker/docker-compose.yml
        dest: "{{ docker_env.PROJECT_SRC }}/docker-compose.yml"
        mode: '0644'

    - name: Ensure Docker Compose services are up
      community.docker.docker_compose_v2:
        project_src: "{{ docker_env.PROJECT_SRC }}"
      environment: "{{ docker_env }}"

    - name: Copy Nginx config files
      copy:
        src: ./docker/nginx/
        dest: "{{ docker_env.PROJECT_SRC }}/nginx/"
      notify: restart_nginx
