---
- hosts: azure
  become: true

  vars_files:
    - vars/vars.yml
    - vars/vault.yml

  handlers:
    - name: update_apt_cache
      apt: 
        update_cache: true

    - name: show_output
      debug:
        var: output

    - name: restart_nginx
      community.docker.docker_compose_v2:
        project_src: docker
        services:
          - nginx
        state: restarted
      register: output
      notify: show_output

  tasks:
    - name: Install required packages
      apt:
        name: ca-certificates
        state: present
        update_cache: yes

    - name: Create directory for Docker keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0755'

    - name: Add Docker repository to APT sources
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      notify: update_apt_cache

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker Compose services are up
      community.docker.docker_compose_v2:
        project_src: docker
      register: output
      notify: show_output

    - name: Copy Nginx config files
      copy:
        src: ./docker/nginx/
        dest: /etc/nginx/
      notify: restart_nginx

