services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-passwd
      MYSQL_PASSWORD_FILE: /run/secrets/db-passwd
    env_file: .env
    secrets:
      - db-root-passwd
      - db-passwd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    env_file: .env
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 8080:80
    networks: 
      - cloud-1
    restart: unless-stopped
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    depends_on:
      mysql: 
        condition: service_healthy
      nginx:
        condition: service_started
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db-passwd
    env_file: .env
    secrets:
      - db-passwd
    volumes:
      - wordpress_data:/var/www/html
    networks: 
      - cloud-1
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: phpmyadmin
    depends_on:
      mysql: 
        condition: service_healthy
    env_file: .env
    ports:
      - 8081:80
    networks:
      - cloud-1
    restart: unless-stopped

networks:
  cloud-1:
    name: cloud-1

volumes:
  wordpress_data:
    name: wordpress_data
  db_data:
    name: db_data

secrets:
  db-root-passwd:
    file: ${PWD}/docker/secrets/db-root-passwd.txt
  db-passwd:
    file: ${PWD}/docker/secrets/db-passwd.txt