services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_SSL_CERT_FILE: ${NGINX_SSL_CERT_FILE}
      NGINX_SSL_KEY_FILE: ${NGINX_SSL_KEY_FILE}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 443:443
      - 80:80
    networks: 
      - cloud-1
    restart: unless-stopped
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    depends_on:
      mysql: 
        condition: service_healthy
      nginx:
        condition: service_started
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
    networks: 
      - cloud-1
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: phpmyadmin
    depends_on:
      mysql: 
        condition: service_healthy
    ports:
      - 8082:80
    networks:
      - cloud-1
    restart: unless-stopped

networks:
  cloud-1:
    name: cloud-1

volumes:
  nginx_conf:
    name: nginx_conf
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_SRC}/nginx/conf.d
  nginx_templates:
    name: nginx_templates
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_SRC}/nginx/templates
  nginx_ssl:
    name: nginx_ssl
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_SRC}/nginx/ssl
  wordpress_data:
    name: wordpress_data
  db_data:
    name: db_data